# Generated by Django 3.0.3 on 2020-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
